server:
  port: 8090

spring:
  kafka:
    bootstrap-servers: localhost:19092,localhost:29092,localhost:39092

receiver:
  order:
    created:
      topic: "order-created"

transmitter:
  payment:
    finished:
      topic: "order-payment-finished"